---
title: "Schedule"
format: 
    html: default
    pdf: default
    docx: default
    rtf: default
---

## Course Schedule

*subject to change*


| Week | **Topic**                          | **Tools**                        |  |
|------|------------------------------------|----------------------------------|---------|
|      | [Preliminaries](assignments/assign1.qmd)
| 1    | [Course Introduction](assignments/assign2.qmd)                | Scripts; R and RStudio  |         |
| 2    | [Reproducible Data Analyses](assignments/assign3.qmd)         | Markup Languages; Quarto     |         |
| 3    | [File Management & Version Control](assignments/assign4.qmd)  | Filesystems; git; GitHub                    |         |
| 4    | [A Field Guide to Data](assignments/assign5.qmd)              | Data Formats; readr; tidyr                       |         |
| 5    | [Structural Data Manipulation](assignments/assign6.qmd)       | dplyr; srvyr                           |         |
| 6    | [Data Visualization I](assignments/assign7.qmd)               | Grammar of Graphics; ggplot2     |         |
| 7    | [Data Visualization II](assignments/assign8.qmd)              | ggplot2                          |         |
| 8    | **Core Exam (Thursday, October 16)** |                                  |         |
| 9    | Social Networks & Network Data     | iGraph; statnet                  |         |
| 10   | Census Data                        | tidycensus                       |         |
| 11   | Maps & GIS I                       | sf; tigris                       |         |
| 12   | Maps & GIS II                      | mapgl; mapbox; osm               |         |
| 13   | Accessing & Using External Data        | SQL, other APIs                              |         |
| 14   | Project Work                       |                                  |         |
| 15   | Project Presentations              |                                  |         |
| F    | **Finals Week (Project Due)**      |                                  |         |

---

*Advanced Topics (if we have time)*

| Week | **Topic**                      | **Tools** |  |
|------|--------------------------------|-----------|---------|
| 16   | Text Data & Data Scraping      |           |         |
| 17   | Web Apps & Visualization       |  quarto, shiny         |         |
| 18   | AI Pair Programming & “Vibe Coding” |  github copilot     |         |
| 19   | Local LLMs                     |           |         |