---
title: "Practicum 1"
format: 
    html: default
    pdf: default
---

## The Task

Replicate Figures 1 and 2 from Bartels (2000), *“Partisanship and Voting Behavior”*,  for the years **2006–2024** using the **Cumulative CCES Dataset**.

---

## The Details

- This Practicum is due **Thursday, October 23, at 2 PM**. *As usual, we will cover the practicum in that class, so late work is not accepted.*

- Turn your exam in to **Blackboard**. You will need to turn in at least two things:  an **R script file** (`.R` or `.qmd`) and a **write-up Quarto document** typeset as a `.pdf`.  You may wish to have more than one R script file.

- The practicum **IS** open-book, open-note, and open-internet, but it **IS NOT** open-human. In short: you can use any resource you want, so long as that resource does not involve asking another human a question. *(The only exception is that you can ask the professor clarification questions.)*

- If you use AI, you must also turn in a record of your prompts as a plain-text `.txt` file. You **MAY** use AI, but *only* to ask questions as you design your own work. You **MAY NOT** feed the entire practicum itself into a chatbot or other AI tool.

- Make sure your write-up document and code script files are **cleanly formatted**. You will be evaluated both for the accuracy of your output and the clarity of your code.

- Follow all the data and style guidelines we have discussed in class. Your `.R` files — once I change the working directory — should properly execute all commands needed to reproduce the results of your practicum, and should do so without any errors. If your `.R` file does not do this, the relevant answers will be considered wrong.

- You may find the **cumulative CCES/CES files** in the course drive.

- In your write-up, make note of any particular challenges you encountered, as well as any significant differences from what you found when replicating Bartels with the ANES.

---

**Good luck!**