---
title: "Bonus Problem Set"
subtitle: "City Maps"
format: 
    html: default
    pdf: default
---

## Introduction

*Note: This is an **optional** assignment, there for those who missed too many regular assignments during the semester and who need to catch up.  If you have completed all of your regular assignments, you may also complete this assignment for a bonus point on your second practicum.*

For this assignment, you will draw city maps using R. You'll need to get your data from OSM (open street maps) as well as (possibly) from other sources, if you have special additions you wish to make.

## Assignment

1. Choose a favorite or interesting area, city, town, or neighborhood (not Syracuse, which we've already done in class).  Identify and select features of the town you'd like to draw: roads (almost certainly), landmarks, water features, parkland, etc. Add those features from OSM and draw a base map for your city or town.

2. Choose two additional features that you'd like to graph in this town.  Is it a ski town, and you want to show where the different ski lodges are?  Is it a mountain town, and you want to show peaks? Do you want to show where all the schools are?  The features are up to you!  Just make two thematic maps - layered on top of the base map - that show particular features of the area. You do not have to use OSM for this part (although you can) - sometimes, it might be easier to just identify the latitude & longitude of points and add them from an external source.

3. Make sure all your maps are compellingly styled and laid out.  Good cartography matters!

::: {.callout-tip}
### Tips
- Remember, OSM can be a little bit finicky, especially in regards to how it will time out with certain requests. Sometimes, you just have to re-run the request, but sometimes, it's becuase your API call is too large. OSM gets more finicky the more you are asking it to do - if you are, for instance, asking it for all roads in the State of New York, it will almost certainly time out.  (That's a lot of roads!)  I recommend choosing a smaller city or town - that tends to be more manageable. Of course, not all cities or states are the same - the same request might do just fine with a particular request looking at a small city like Ithaca, but time out with New York City itself.  You might also have more luck asking for fewer features at the same time, or spacing your reqeuests out a little bit.
:::

## Submission

Turn in 4 things:

1. Your R script(s).
2. A quarto file that addresses or answers the steps above and includes your graphics.  Your quarto file can include your R code or your R code can remain separate in your R scripts, with the quarto file reading in figures from project directory.
3. A compiled quarto file, as a PDF, that includes your maps.
4. Your original data, if necessary, in a format readable by R.  (If you read data directly from a web source in your script, you can skip this step.)

Make sure that your quarto writeup includes a clear definition of the maps you drew, as well as a summary description of what is particularly noteworthy about the features of your maps. It should also document the source of the data, especially if different than OSM, and note steps done to manage the data (if any) before your R script(s) took over.

::: {.callout-note}
### Important

To submit your assignment, zip your entire project folder together - including all of the above elements - and upload it to Blackboard.  Alternately, you may store everything in a GitHub repo and submit a link to your repository to Blackboard.
:::