---
title: "Problem Set 8"
subtitle: "The Policy Agendas Project"
---

## Introduction

The United States Policy Agendas Project, housed jointly at University of Texas-Austin and Syracuse University, is part of the broader Comparative Agendas Project. It "collects and organizes data from various archived sources tracing changes in the U.S. national policy agenda and public policy outcomes since the WWII. The project's datasets span from 1901-2068 and have close to one million observations."[^pap]

[^pap]: [Source](https://www.maxwell.syr.edu/research/campbell-public-affairs-institute/united-states-policy-agendas-project) 

Links:

- [Comparative Agendas Project](https://www.comparativeagendas.net)
- [United States Datasets](https://www.comparativeagendas.net/project/us/datasets)
- [Policy Agendas Project Info Page at UT Austin](https://liberalarts.utexas.edu/government/news/feature-archive/the-policy-agendas-project.html)
- [Policy Agendas Project Info Page at Syracuse/Maxwell](https://www.maxwell.syr.edu/research/campbell-public-affairs-institute/united-states-policy-agendas-project)
- [Data Pages at Syracuse](https://www.maxwell.syr.edu/research/campbell-public-affairs-institute/united-states-policy-agendas-project/datasets-and-codebooks)
- [Training Pages at Syracuse](https://www.maxwell.syr.edu/research/campbell-public-affairs-institute/united-states-policy-agendas-project/training-modules)

## Assignment

Explore the Policy Agendas project pages and get comfortable with what the project is and what kind of data it has.  You are not required to go through any particular aspect of the above pages (for instance, I don't expect you to watch the training videos unless you want to) but all are there as resources to orient yourself to the project.

Once you are familiar with it, use **multiple** Policy Agendas project datasets to visualize how attention has varied across major policy/topic areas from 1950 (or prior) to the present.  This assignment is inherently open-ended - each of you should come up with a different visualization - and I encourage creativity in both substance and visualization style.

You can use any data you find on the pages, including data from other countries if you wish, in creating your graphs. 

## Submission

Turn in four things:

1. An .R script (or scripts) that reproduce your analysis, in full, from original data files available from the Policy Agendas project.  
    - Your code should use at least two different data files and produce three different graphs (each of your choosing.)  
    - Make sure you explicitly note what datasets you are using in a comment, so I know - don't just load the data.
    - Use an R project to organize your work.

2. A Quarto file that writes up and explains what you are showing.

3. A rendered/typeset PDF file from that quarto file.  This file should include all of your graphs.

4. If you do not load data directly from the web, upload the datasets that you use in your R script. 

Next week, as we go over our assignments, we'll do a "Show and Tell", so be prepared to talk about your visualizations in class!

::: {.callout-note}
### Important

To submit your assignment, zip your entire project folder together - including all of the above elements - and upload it to Blackboard.  Alternately, you may store everything in a GitHub repo and submit a link to your repository to Blackboard.
:::


::: callout-tip

Note that if you are using a .csv file from an online web location with a persistent hyperlink, you can read that file directly into R, once you identify the URL, like this:

```r
# This reads in the budget and tax dataset from the Syracuse webpage
data<-read.csv("https://www.maxwell.syr.edu/docs/default-source/research/campbell/us-policy-agendas-project/budget-tax-dataset.csv")

# This reads in the NYTimes front page dataset from the comparative agendas project webpage
nytimes<-read.csv("https://minio.la.utexas.edu/compagendas/datasetfiles/US-Media-NYTimes_front_page_19.3.csv")
```

It is always a good idea to make sure you have a local copy of the file, as well, just in case something changes with the online file or your web access.

:::