---
title: "Week 12: Geographic Data"
format: 
    html: default
    pdf: default
---

## Due This Week: [Problem Set 10](../problemsets/ps10.qmd)

## Readings & Reference Material

### Lecture: Geographic Data

### Reading

- Core Reading
    - **DMSS**, ch 11
- Vignettes
    - [How to make fancy road trip maps with R and OpenStreetMap](https://www.andrewheiss.com/blog/2023/06/01/geocoding-routing-openstreetmap-r/)
    - [Making Middle Earth Maps in R](https://www.andrewheiss.com/blog/2023/04/26/middle-earth-mapping-sf-r-gis/)
- Reference Materials
    - Brunsdon and Comber, *An Introduction to R for Spatial Analysis and Mapping*.  An excellent introdution to using R as a GIS package.
    - Brunsdon and Comber, *Geographical Data Science and Spatial Data Analysis: An Introduction in R*.  Despite its name, a companion book to the above, not a replacement.  It's a little higher level.
    - Lovelace, et al. *Geocomputation with R*.  A more in depth guide to spatial data in R.
    - Bivand, et al. *Applied Spatial Data Anlaysis with R*. Another more in depth guide to spatial data in R.
    - Singleton, et al. *Urban Anlaytics*.


## Due Next Week: Final Project Identification
