---
title: "Week 6. Data Visualization I"
subtitle: "Assignment: The American National Election Studies (Due Week 7)"
---

***in progress***

## Readings & Reference Material
### Lecture: Data Visualization I
- **DV**, chs 3-4
- **RDS**, chs 9-10
- **FCSP**, ch 3

## Data Work
1. Read Bartels (2000) - “Partisanship and Voting Behavior, 1952-1996”. Using the Cumulative American National Eleciton Studies (ANES) file, replicate Figures 1 and 2.

2. Extend the analysis to include recent years as well.

3. Extend the analysis to 2024, using the 2024 ANES file.  (This will require using the 2024 file in conjuction with the cumulative file.)

3. Create figures that include midterm election years as well.

2. Original Work: explore the codebook for the ANES.  Find two interesting variables and create compelling univariate graphs to illustrate their central tendency, distribution, and spread.

## Submission (Due Week 7)

Your completed assignment should include a copy of your .R script file(s) (with comments, etc) used to code the variables and do the analysis, a .quarto file that contains your writeup and figures, and a .PDF file with all of your (properly labeled and attractively laid out) tables/figures.

In your writeup, address the following questions:

1. Where did you encounter problems with this replication?  Was there anything that was particular tricky?

2. How would you *interpret* (explain) what Bartels found in figures 1 & 2?  

3. Has anything changed since 1998 that would alter the substantive takeaway points in their findings?

4. Does anything change about the analysis in a substantive way when you include midterm election years?