---
title: "Week 5. Structural Data Manipulation"
subtitle: "Assignment: The General Social Survey (Due Week 6)"
---

***in progress***

## Readings & Reference Material
### Lecture: Structural Data Manipulation

- **DMSS**, ch 5, 6, & 7
- **RDS**, chs 3-6
- **FCSP**, ch 5.4-5.6

## Data Work
1. Replication: Read Mondak and Sanders (2003) - “Tolerance and Intolerance, 1976-1998”.  Using the Cumulative General Social Survey (GSS) file, replicate Figures 1, 2, and 5. (Don’t worry about getting the particular value arrows in your graph.) 

2. Extend the analysis to include more recent years as well. 

2. Original Work: explore the codebook for the GSS.  Find two interesting variables and create compelling univariate graphs to illustrate their central tendency, distribution, and spread.

## Submission 

Your completed assignment should include a copy of your .R script file(s) (with comments, etc) used to code the variables and do the analysis, a .quarto file that contains your writeup and figures, and a .PDF file with all of your (properly labeled and attractively laid out) tables/figures.

In your writeup, address the following questions:

1. Where did you encounter problems with this replication?  Was there anything that was particular tricky?

2. How would you *interpret* (explain) what Mondak and Saunders found in figures 1, 2, and 5?  

3. Has anything changed since 1998 that would alter the substantive takeaway points in their findings?