---
title: "Course Setup"
subtitle: "Assignment: Hello & Welcome to R (Due Week 1)"
---

## Readings

- Read the course syllabus (all parts of [this website](../index.qmd))
- Recommended reading:
   - **RDS**, introduction

## Data & Computational Work

The main purpose of this week's assignment is to get your computer ready for all the work in the class.  This means, primarily, installing software.

### Install R on your computer

Begin by installing R (<http://cloud.r-project.org>). Choose the version appropriate for your computing platform:

- If you use macOS with an Apple Silicon processor (i.e. an M-series processor), then install [R for macOS's Apple Silicon build](https://cloud.r-project.org/bin/macosx/big-sur-arm64/base/R-4.5.1-arm64.pkg). This version does not work on older, Intel-based Macs.

- If you use macOS with an Intel processor, then install [R for macOS's Intel build](https://cloud.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.5.1-x86_64.pkg).

- If you use Microsoft Windows, then install [R for Windows](https://cloud.r-project.org/bin/windows/base/R-4.5.1-win.exe).

- If you use Linux, [choose your distribution](https://cloud.r-project.org/bin/linux/) and install the R package for it.

### Install RStudio on your computer

- If you use macOS (whether Apple Silicon or Intel), [install this version of RStudio](https://download1.rstudio.org/electron/macos/RStudio-2025.05.1-513.dmg).

- If you use Windows, [install this version of RStudio](https://download1.rstudio.org/electron/windows/RStudio-2025.05.1-513.exe).

- If you use Linux, [choose your distribution from the download page](https://posit.co/download/rstudio-desktop/).

### Confirm things work

- R is really a great big calculator.  Let's do some calculations!
   - Add 2 and 3 together
 	- Multiply 4 by 6
 	- Divide 10 by 5

## Submit: .R File  (Optional)

In an .R file, write code to answer the following questions. Make sure your file is appropriately titled and headered.

*Note: You can submit this R file in Week 2, if you prefer.*

1. Create an object named `aardvark` that stores a 3 as a single number
2. Create a second object named `boomba` that stores a 6 as a single number
3. Create a third object named `centauri` that is the addition of `aardvark` and `boomba`
4. Create a fourth object named `diabolical` that is the multiplication `aardvark` and `boomba`
5. Create an object named `ebullient` that stores three numbers as a vector: 4,5,and 6
6. Create an object named `fastidious` that stores three numbers as a vector: 8,9, and 11
7. Add `ebullient` and `fastidious` together, and store it in an object named `george`
8. Find the mean (average) of `fastidious`, and store it in an object named `zoinks`

## Submit: PDF file

Answer the following questions and upload as a PDF to Blackboard.

1. What is your name and program of study at Syracuse?  
   *(Optional: provide your pronouns, if you wish.)*

2. What is your prior experience with statistics, data analysis, R, and computer programming generally?  

3. What are you hoping to get out of this class?  

4. Please include a picture of yourself!  
   - It can be anything – just make sure that you are the only person in the picture so I can clearly identify you.  

5. What is the mean of the `fastidious` object from your .R assignment above?